CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE links ADD COLUMN user_id INT;
ALTER TABLE links ADD CONSTRAINT fk_links_user FOREIGN KEY (user_id) REFERENCES users(id);

CREATE INDEX idx_links_user_id ON links(user_id);
